version: "3.3"
services:
  server:
    image: test/ipc
    build: .
    environment:
      - "MODE=server"
    volumes:
      - "shared:/var/run"
  client1:
    image: test/ipc
    depends_on:
      - server
    environment:
      - "MODE=client"
    volumes:
      - "shared:/var/run"
  client2:
    image: test/ipc
    depends_on:
      - server
    environment:
      - "MODE=client"
    volumes:
      - "shared:/var/run"
    command: "sh -c 'echo foo | node index.js'"
volumes:
  shared:
